services:
  timer-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=development

  timer-app-prod:
    build: .
    ports:
      - "80:80"